#!/bin/bash
# File: runtime/generate_engine.sh
# Generates app/src/main/cpp/native-lib.cpp
# This is the AUTHORITATIVE C++ OpenGL ES 3.0 engine for EndlessRPG.

set -e
mkdir -p app/src/main/cpp

cat << 'EOF' > app/src/main/cpp/native-lib.cpp
// ============================================================
//  EndlessRPG — native-lib.cpp
//  OpenGL ES 3.0 engine.  Compiled via CMake + Android NDK.
//  JNI entry points match MainActivity.java exactly.
// ============================================================
#include <jni.h>
#include <GLES3/gl3.h>
#include <android/log.h>
#include <cmath>
#include <cstring>
#include <vector>
#include <algorithm>

// Generated by runtime/build_models.py (Blender bake)
#include "models/AllModels.h"

#define LOG_TAG "EndlessRPG"
#define LOGI(...) __android_log_print(ANDROID_LOG_INFO, LOG_TAG, __VA_ARGS__)
#define LOGE(...) __android_log_print(ANDROID_LOG_ERROR, LOG_TAG, __VA_ARGS__)

// ─────────────────────────────────────────────────────────────
//  Math
// ─────────────────────────────────────────────────────────────
struct Vec3 { float x, y, z; };
struct Mat4 { float m[16]; };

static Mat4 mat4_identity() {
    Mat4 r; memset(r.m, 0, sizeof(r.m));
    r.m[0] = r.m[5] = r.m[10] = r.m[15] = 1.0f;
    return r;
}
static Mat4 mat4_mul(const Mat4& a, const Mat4& b) {
    Mat4 r; memset(r.m, 0, sizeof(r.m));
    for (int i = 0; i < 4; i++)
        for (int j = 0; j < 4; j++)
            for (int k = 0; k < 4; k++)
                r.m[i*4+j] += a.m[k*4+j] * b.m[i*4+k];
    return r;
}
static Mat4 mat4_perspective(float fovY, float aspect, float zn, float zf) {
    Mat4 r = mat4_identity();
    float f = 1.0f / tanf(fovY * 0.5f);
    r.m[0]  =  f / aspect;
    r.m[5]  =  f;
    r.m[10] = -(zf + zn) / (zf - zn);
    r.m[11] = -1.0f;
    r.m[14] = -(2.0f * zf * zn) / (zf - zn);
    r.m[15] =  0.0f;
    return r;
}
static Mat4 mat4_lookat(Vec3 eye, Vec3 center, Vec3 up) {
    auto norm = [](Vec3 v) -> Vec3 {
        float l = sqrtf(v.x*v.x + v.y*v.y + v.z*v.z);
        return {v.x/l, v.y/l, v.z/l};
    };
    auto cross = [](Vec3 a, Vec3 b) -> Vec3 {
        return {a.y*b.z - a.z*b.y, a.z*b.x - a.x*b.z, a.x*b.y - a.y*b.x};
    };
    auto dot = [](Vec3 a, Vec3 b) -> float { return a.x*b.x + a.y*b.y + a.z*b.z; };

    Vec3 f = norm({center.x-eye.x, center.y-eye.y, center.z-eye.z});
    Vec3 s = norm(cross(f, up));
    Vec3 u = cross(s, f);

    Mat4 r = mat4_identity();
    r.m[0]=s.x; r.m[4]=s.y; r.m[8] =s.z;
    r.m[1]=u.x; r.m[5]=u.y; r.m[9] =u.z;
    r.m[2]=-f.x;r.m[6]=-f.y;r.m[10]=-f.z;
    r.m[12]=-dot(s,eye); r.m[13]=-dot(u,eye); r.m[14]=dot(f,eye);
    return r;
}
static Mat4 mat4_translate(float x, float y, float z) {
    Mat4 r = mat4_identity();
    r.m[12] = x; r.m[13] = y; r.m[14] = z;
    return r;
}
static Mat4 mat4_scale(float x, float y, float z) {
    Mat4 r = mat4_identity();
    r.m[0] = x; r.m[5] = y; r.m[10] = z;
    return r;
}
static Mat4 mat4_rotX(float a) {
    Mat4 r = mat4_identity();
    r.m[5]=cosf(a); r.m[6]=sinf(a); r.m[9]=-sinf(a); r.m[10]=cosf(a);
    return r;
}
static Mat4 mat4_rotY(float a) {
    Mat4 r = mat4_identity();
    r.m[0]=cosf(a); r.m[2]=-sinf(a); r.m[8]=sinf(a); r.m[10]=cosf(a);
    return r;
}

// ─────────────────────────────────────────────────────────────
//  Procedural terrain height  (5-octave fBm)
// ─────────────────────────────────────────────────────────────
static float hash2(float x, float y) {
    float v = sinf(x * 127.1f + y * 311.7f) * 43758.5453f;
    return v - floorf(v);
}
static float vnoise(float x, float y) {
    float ix = floorf(x), iy = floorf(y);
    float fx = x - ix,    fy = y - iy;
    float ux = fx*fx*(3.0f - 2.0f*fx);
    float uy = fy*fy*(3.0f - 2.0f*fy);
    float a = hash2(ix,   iy);
    float b = hash2(ix+1, iy);
    float c = hash2(ix,   iy+1);
    float d = hash2(ix+1, iy+1);
    return a + (b-a)*ux + (c-a)*uy + (d-b+a-c)*ux*uy;
}
static float terrainH(float wx, float wz) {
    float v = 0.0f, a = 0.55f, s = 0.18f;
    for (int i = 0; i < 5; i++) {
        v += a * vnoise(wx * s, wz * s);
        s *= 2.1f; a *= 0.50f;
    }
    return v * 9.5f - 0.6f;   // -0.6 puts flat areas near y=0
}

// ─────────────────────────────────────────────────────────────
//  Shader source (embedded)
// ─────────────────────────────────────────────────────────────
static const char* VS_SRC = R"GLSL(#version 300 es
precision highp float;
layout(location=0) in vec3 aPos;
layout(location=1) in vec3 aColor;

uniform mat4 uModel;
uniform mat4 uViewProj;
uniform vec3 uSunDir;

out vec3 vColor;
out vec3 vWorldPos;
out vec3 vNormal;

void main() {
    vec4 wp      = uModel * vec4(aPos, 1.0);
    vWorldPos    = wp.xyz;
    vColor       = aColor;
    // Cheap normal: rotate world-up by model rotation
    mat3 normalMat = mat3(uModel);
    vNormal      = normalize(normalMat * vec3(0.0, 1.0, 0.0));
    gl_Position  = uViewProj * wp;
}
)GLSL";

static const char* FS_SRC = R"GLSL(#version 300 es
precision highp float;

in vec3 vColor;
in vec3 vWorldPos;
in vec3 vNormal;

uniform vec3  uSunDir;
uniform vec3  uSkyColor;
uniform vec3  uCamPos;
uniform float uFogStart;
uniform float uFogEnd;

out vec4 FragColor;

void main() {
    // Hemisphere ambient
    vec3 skyAmb    = vec3(0.42, 0.52, 0.68);
    vec3 groundAmb = vec3(0.14, 0.12, 0.09);
    float hemi     = vNormal.y * 0.5 + 0.5;
    vec3 ambient   = mix(groundAmb, skyAmb, hemi) * 0.38;

    // Lambertian diffuse
    float NdotL  = max(dot(vNormal, uSunDir), 0.0);
    vec3  diffuse = vColor * NdotL * 0.78;

    // Blinn-Phong specular (subtle gloss)
    vec3  viewDir  = normalize(uCamPos - vWorldPos);
    vec3  halfVec  = normalize(uSunDir + viewDir);
    float specPow  = pow(max(dot(vNormal, halfVec), 0.0), 56.0);
    vec3  specular = vec3(0.10) * specPow;

    vec3 lit = ambient + diffuse + specular;

    // Quadratic exponential fog
    float dist      = length(uCamPos - vWorldPos);
    float fog       = clamp((dist - uFogStart) / (uFogEnd - uFogStart), 0.0, 1.0);
    fog             = fog * fog;

    vec3 color = mix(lit, uSkyColor, fog);
    FragColor  = vec4(color, 1.0);
}
)GLSL";

// ─────────────────────────────────────────────────────────────
//  GL helpers
// ─────────────────────────────────────────────────────────────
static GLuint compileShader(GLenum type, const char* src) {
    GLuint s = glCreateShader(type);
    glShaderSource(s, 1, &src, nullptr);
    glCompileShader(s);
    GLint ok; glGetShaderiv(s, GL_COMPILE_STATUS, &ok);
    if (!ok) {
        char buf[512]; glGetShaderInfoLog(s, 512, nullptr, buf);
        LOGE("Shader error: %s", buf);
    }
    return s;
}

static GLuint createProgram(const char* vs, const char* fs) {
    GLuint p = glCreateProgram();
    glAttachShader(p, compileShader(GL_VERTEX_SHADER, vs));
    glAttachShader(p, compileShader(GL_FRAGMENT_SHADER, fs));
    glLinkProgram(p);
    GLint ok; glGetProgramiv(p, GL_LINK_STATUS, &ok);
    if (!ok) { char b[512]; glGetProgramInfoLog(p, 512, nullptr, b); LOGE("Link: %s", b); }
    return p;
}

// VAO for position+colour data (6 floats per vertex, stride=24)
static GLuint makeVAO(const float* data, int vertCount) {
    GLuint vao, vbo;
    glGenVertexArrays(1, &vao);
    glGenBuffers(1, &vbo);
    glBindVertexArray(vao);
    glBindBuffer(GL_ARRAY_BUFFER, vbo);
    glBufferData(GL_ARRAY_BUFFER, (GLsizeiptr)(vertCount * 6 * sizeof(float)),
                 data, GL_STATIC_DRAW);
    glVertexAttribPointer(0, 3, GL_FLOAT, GL_FALSE, 24, (void*)0);
    glEnableVertexAttribArray(0);
    glVertexAttribPointer(1, 3, GL_FLOAT, GL_FALSE, 24, (void*)12);
    glEnableVertexAttribArray(1);
    glBindVertexArray(0);
    return vao;
}

// ─────────────────────────────────────────────────────────────
//  Runtime terrain mesh generation
// ─────────────────────────────────────────────────────────────
static const int  TERRAIN_CELLS = 64;    // cells per side
static const float TERRAIN_SCALE = 1.0f; // world units per cell
static GLuint  g_vaoTerrain = 0;
static GLuint  g_vboTerrain = 0;
static GLuint  g_iboTerrain = 0;
static int     g_terrainIdxCount = 0;

static void buildTerrain() {
    int N = TERRAIN_CELLS + 1;
    std::vector<float>    verts;
    std::vector<uint32_t> idx;
    verts.reserve(N * N * 6);
    idx  .reserve(TERRAIN_CELLS * TERRAIN_CELLS * 6);

    float half = TERRAIN_CELLS * TERRAIN_SCALE * 0.5f;

    for (int z = 0; z < N; z++) {
        for (int x = 0; x < N; x++) {
            float wx = x * TERRAIN_SCALE - half;
            float wz = z * TERRAIN_SCALE - half;
            float wy = terrainH(wx, wz);

            // Normal via finite differences
            float hL = terrainH(wx - 0.1f, wz);
            float hR = terrainH(wx + 0.1f, wz);
            float hD = terrainH(wx, wz - 0.1f);
            float hU = terrainH(wx, wz + 0.1f);
            float nx = hL - hR, nz = hD - hU, ny = 0.2f;
            float nl = sqrtf(nx*nx + ny*ny + nz*nz);
            nx /= nl; ny /= nl; nz /= nl;

            // Height-based colour: grass → dirt → rock
            float t = wy / 5.0f;
            float r, g, b;
            if (t < 0.2f) {
                // Low: wet soil / mud
                r = 0.28f; g = 0.20f; b = 0.10f;
            } else if (t < 0.65f) {
                // Mid: lush grass
                float ft = (t - 0.2f) / 0.45f;
                r = 0.16f + ft * 0.08f;
                g = 0.40f + ft * 0.06f;
                b = 0.12f + ft * 0.04f;
            } else {
                // High: rocky outcrop
                float ft = std::min((t - 0.65f) / 0.35f, 1.0f);
                r = 0.24f + ft * 0.28f;
                g = 0.20f + ft * 0.24f;
                b = 0.16f + ft * 0.20f;
            }

            // AO darkening at depression troughs (very subtle)
            float ao = 0.82f + 0.18f * std::max(ny, 0.0f);
            verts.push_back(wx); verts.push_back(wy); verts.push_back(wz);
            verts.push_back(r * ao); verts.push_back(g * ao); verts.push_back(b * ao);
        }
    }
    for (int z = 0; z < TERRAIN_CELLS; z++) {
        for (int x = 0; x < TERRAIN_CELLS; x++) {
            uint32_t s = z * N + x;
            idx.push_back(s);     idx.push_back(s + N); idx.push_back(s + 1);
            idx.push_back(s + 1); idx.push_back(s + N); idx.push_back(s + N + 1);
        }
    }
    g_terrainIdxCount = (int)idx.size();

    glGenVertexArrays(1, &g_vaoTerrain);
    glGenBuffers(1, &g_vboTerrain);
    glGenBuffers(1, &g_iboTerrain);
    glBindVertexArray(g_vaoTerrain);
    glBindBuffer(GL_ARRAY_BUFFER, g_vboTerrain);
    glBufferData(GL_ARRAY_BUFFER, verts.size() * sizeof(float), verts.data(), GL_STATIC_DRAW);
    glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, g_iboTerrain);
    glBufferData(GL_ELEMENT_ARRAY_BUFFER, idx.size() * sizeof(uint32_t), idx.data(), GL_STATIC_DRAW);
    glVertexAttribPointer(0, 3, GL_FLOAT, GL_FALSE, 24, (void*)0);  glEnableVertexAttribArray(0);
    glVertexAttribPointer(1, 3, GL_FLOAT, GL_FALSE, 24, (void*)12); glEnableVertexAttribArray(1);
    glBindVertexArray(0);
}

// ─────────────────────────────────────────────────────────────
//  Global engine state
// ─────────────────────────────────────────────────────────────
static GLuint g_prog = 0;
static GLuint g_vaoTorso=0, g_vaoHead=0, g_vaoUpLimb=0, g_vaoLowLimb=0;
static GLuint g_vaoFoot=0,  g_vaoSword=0, g_vaoShield=0, g_vaoTree=0;

// Uniform cache
static GLint  uModel=0, uViewProj=0, uSunDir=0,
              uSkyColor=0, uCamPos=0, uFogStart=0, uFogEnd=0;

// Player state
static float g_px = 0.f, g_py = 0.f, g_pz = 0.f;
static float g_facing = 0.f;
static float g_walkT  = 0.f;
static float g_jumpVY = 0.f;
static float g_jumpY  = 0.f;

// Animation timers
static float g_slashT = 0.f;
static float g_bashT  = 0.f;
static bool  g_block  = false;

// Camera (set from Java each frame)
static float g_camYaw   = 0.7f;
static float g_camPitch = 0.45f;
static float g_camZoom  = 13.0f;

static Mat4  g_proj;
static float g_aspect = 1.0f;

// Sky colour (also used for fog)
static const float SKY_R = 0.47f, SKY_G = 0.63f, SKY_B = 0.88f;

// Sun direction (normalised, points toward sun)
static const float SUN_X = 0.36f, SUN_Y = 0.88f, SUN_Z = 0.30f;

// ─────────────────────────────────────────────────────────────
//  Draw helpers
// ─────────────────────────────────────────────────────────────
static void setModel(const Mat4& m) {
    glUniformMatrix4fv(uModel, 1, GL_FALSE, m.m);
}
static void drawVAO(GLuint vao, int count) {
    glBindVertexArray(vao);
    glDrawArrays(GL_TRIANGLES, 0, count);
}

// ─────────────────────────────────────────────────────────────
//  Character assembly
// ─────────────────────────────────────────────────────────────
static void drawCharacter(const Mat4& base) {

    // --- Torso ---
    setModel(base);
    drawVAO(g_vaoTorso, N_TORSO);

    // --- Head ---
    Mat4 mHead = mat4_mul(base, mat4_translate(0.0f, 0.90f, 0.0f));
    setModel(mHead);
    drawVAO(g_vaoHead, N_HEAD);

    // --- Arms ---
    // Right arm (sword side): swings during attack
    float swRot = (g_slashT > 0.0f)
                  ? -2.4f * sinf(g_slashT * 3.14159f)
                  : -sinf(g_walkT) * 0.45f;
    Mat4 mRArm = mat4_mul(base, mat4_translate( 0.40f, 0.55f, 0.0f));
    mRArm = mat4_mul(mRArm, mat4_rotX(swRot));
    setModel(mRArm);                           drawVAO(g_vaoUpLimb, N_UP_LIMB);
    Mat4 mRFore = mat4_mul(mRArm, mat4_translate(0.0f, -0.44f, 0.0f));
    setModel(mRFore);                          drawVAO(g_vaoLowLimb, N_LOW_LIMB);
    Mat4 mRHand = mat4_mul(mRFore, mat4_translate(0.0f, -0.42f, 0.0f));
    setModel(mRHand);                          drawVAO(g_vaoFoot, N_FOOT);
    // Sword in right hand
    Mat4 mSword = mat4_mul(mRHand, mat4_translate(0.0f, -0.25f, 0.0f));
    setModel(mSword);                          drawVAO(g_vaoSword, N_SWORD);

    // Left arm (shield side): raised when blocking
    float shRot = g_block ? -1.5f : (g_bashT > 0.f ? -1.75f : sinf(g_walkT) * 0.45f);
    Mat4 mLArm = mat4_mul(base, mat4_translate(-0.40f, 0.55f, 0.0f));
    mLArm = mat4_mul(mLArm, mat4_rotX(shRot));
    setModel(mLArm);                           drawVAO(g_vaoUpLimb, N_UP_LIMB);
    Mat4 mLFore = mat4_mul(mLArm, mat4_translate(0.0f, -0.44f, 0.0f));
    setModel(mLFore);                          drawVAO(g_vaoLowLimb, N_LOW_LIMB);
    Mat4 mLHand = mat4_mul(mLFore, mat4_translate(0.0f, -0.42f, 0.0f));
    // Shield on left forearm, rotated upright
    Mat4 mShield = mat4_mul(mLHand, mat4_translate(0.0f, -0.15f, 0.08f));
    mShield = mat4_mul(mShield, mat4_rotX(1.5708f));
    setModel(mShield);                         drawVAO(g_vaoShield, N_SHIELD);

    // --- Legs ---
    float legSwing = sinf(g_walkT) * 0.65f;
    // Right leg
    Mat4 mRLeg  = mat4_mul(base, mat4_translate( 0.20f, -0.08f, 0.0f));
    mRLeg = mat4_mul(mRLeg, mat4_rotX(-legSwing));
    setModel(mRLeg);                           drawVAO(g_vaoUpLimb, N_UP_LIMB);
    Mat4 mRShin = mat4_mul(mRLeg, mat4_translate(0.0f, -0.44f, 0.0f));
    // Knee bend: forward leg bends back
    float rKnee = std::max(0.0f, -legSwing) * 0.6f;
    mRShin = mat4_mul(mRShin, mat4_rotX(rKnee));
    setModel(mRShin);                          drawVAO(g_vaoLowLimb, N_LOW_LIMB);
    Mat4 mRFoot = mat4_mul(mRShin, mat4_translate(0.0f, -0.44f, 0.0f));
    setModel(mRFoot);                          drawVAO(g_vaoFoot, N_FOOT);

    // Left leg
    Mat4 mLLeg  = mat4_mul(base, mat4_translate(-0.20f, -0.08f, 0.0f));
    mLLeg = mat4_mul(mLLeg, mat4_rotX( legSwing));
    setModel(mLLeg);                           drawVAO(g_vaoUpLimb, N_UP_LIMB);
    Mat4 mLShin = mat4_mul(mLLeg, mat4_translate(0.0f, -0.44f, 0.0f));
    float lKnee = std::max(0.0f,  legSwing) * 0.6f;
    mLShin = mat4_mul(mLShin, mat4_rotX(lKnee));
    setModel(mLShin);                          drawVAO(g_vaoLowLimb, N_LOW_LIMB);
    Mat4 mLFoot = mat4_mul(mLShin, mat4_translate(0.0f, -0.44f, 0.0f));
    setModel(mLFoot);                          drawVAO(g_vaoFoot, N_FOOT);
}

// ─────────────────────────────────────────────────────────────
//  JNI exports
// ─────────────────────────────────────────────────────────────
extern "C" {

JNIEXPORT void JNICALL
Java_com_game_procedural_MainActivity_onCreated(JNIEnv*, jobject) {
    g_prog = createProgram(VS_SRC, FS_SRC);

    // Cache uniforms
    uModel     = glGetUniformLocation(g_prog, "uModel");
    uViewProj  = glGetUniformLocation(g_prog, "uViewProj");
    uSunDir    = glGetUniformLocation(g_prog, "uSunDir");
    uSkyColor  = glGetUniformLocation(g_prog, "uSkyColor");
    uCamPos    = glGetUniformLocation(g_prog, "uCamPos");
    uFogStart  = glGetUniformLocation(g_prog, "uFogStart");
    uFogEnd    = glGetUniformLocation(g_prog, "uFogEnd");

    // Upload model geometry
    g_vaoTorso   = makeVAO(M_TORSO,   N_TORSO);
    g_vaoHead    = makeVAO(M_HEAD,    N_HEAD);
    g_vaoUpLimb  = makeVAO(M_UP_LIMB, N_UP_LIMB);
    g_vaoLowLimb = makeVAO(M_LOW_LIMB,N_LOW_LIMB);
    g_vaoFoot    = makeVAO(M_FOOT,    N_FOOT);
    g_vaoSword   = makeVAO(M_SWORD,   N_SWORD);
    g_vaoShield  = makeVAO(M_SHIELD,  N_SHIELD);
    g_vaoTree    = makeVAO(M_TREE,    N_TREE);

    buildTerrain();

    glEnable(GL_DEPTH_TEST);
    glDepthFunc(GL_LESS);
    glEnable(GL_CULL_FACE);
    glCullFace(GL_BACK);
    glClearColor(SKY_R, SKY_G, SKY_B, 1.0f);

    LOGI("Engine initialised.");
}

JNIEXPORT void JNICALL
Java_com_game_procedural_MainActivity_onChanged(JNIEnv*, jobject, jint w, jint h) {
    glViewport(0, 0, w, h);
    g_aspect = (h > 0) ? (float)w / (float)h : 1.0f;
    g_proj   = mat4_perspective(1.047f, g_aspect, 0.1f, 160.0f);
    LOGI("Surface %dx%d", w, h);
}

JNIEXPORT void JNICALL
Java_com_game_procedural_MainActivity_onDraw(
        JNIEnv*, jobject,
        jfloat ix, jfloat iy,
        jfloat yaw, jfloat pitch, jfloat zoom)
{
    // Store camera params
    g_camYaw   = yaw;
    g_camPitch = pitch;
    g_camZoom  = zoom;

    // ── Physics / Movement ─────────────────────────────────
    const float SPEED = 0.12f;
    bool moving = (fabsf(ix) > 0.02f || fabsf(iy) > 0.02f);
    if (moving) {
        float sinY = sinf(yaw), cosY = cosf(yaw);
        float dx =  ix * cosY - (-iy) * sinY;
        float dz =  ix * sinY + (-iy) * cosY;
        g_px    += dx * SPEED;
        g_pz    -= dz * SPEED;
        g_facing = atan2f(-dx, dz);
        g_walkT += 0.18f;
    }

    // Jump physics
    g_jumpY  += g_jumpVY;
    g_jumpVY -= 0.022f;
    float gh  = terrainH(g_px, g_pz);
    if (g_jumpY <= gh) { g_jumpY = gh; g_jumpVY = 0.f; }
    g_py = g_jumpY;

    // Animation decay
    if (g_slashT > 0.f) g_slashT -= 0.055f;
    if (g_bashT  > 0.f) g_bashT  -= 0.085f;

    // ── Camera ─────────────────────────────────────────────
    float safeZoom = std::max(5.0f, zoom);
    float eyeX = g_px - sinf(yaw) * cosf(pitch) * safeZoom;
    float eyeZ = g_pz - cosf(yaw) * cosf(pitch) * safeZoom;
    float eyeY = g_py + sinf(pitch) * safeZoom + 1.4f;
    Vec3  eye    = {eyeX, eyeY, eyeZ};
    Vec3  center = {g_px, g_py + 1.2f, g_pz};
    Mat4  view   = mat4_lookat(eye, center, {0.f, 1.f, 0.f});
    Mat4  vp     = mat4_mul(g_proj, view);

    // ── Render ─────────────────────────────────────────────
    glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);
    glUseProgram(g_prog);

    glUniformMatrix4fv(uViewProj, 1, GL_FALSE, vp.m);
    glUniform3f(uSunDir,   SUN_X, SUN_Y, SUN_Z);
    glUniform3f(uSkyColor, SKY_R, SKY_G, SKY_B);
    glUniform3f(uCamPos,   eyeX, eyeY, eyeZ);
    glUniform1f(uFogStart, safeZoom * 3.5f);
    glUniform1f(uFogEnd,   safeZoom * 7.5f);

    // 1. Terrain
    Mat4 terrainM = mat4_identity();
    setModel(terrainM);
    glBindVertexArray(g_vaoTerrain);
    glDrawElements(GL_TRIANGLES, g_terrainIdxCount, GL_UNSIGNED_INT, nullptr);

    // 2. Trees — procedurally placed on terrain
    for (int i = -4; i <= 4; i++) {
        for (int j = -4; j <= 4; j++) {
            float tx = floorf(g_px / 10.0f) * 10.0f + i * 10.0f;
            float tz = floorf(g_pz / 10.0f) * 10.0f + j * 10.0f;
            // Deterministic filter so not every cell has a tree
            float h1 = hash2(tx * 0.05f, tz * 0.07f);
            if (h1 < 0.45f) continue;
            float ty = terrainH(tx, tz);
            // Skip if terrain is too steep / rocky (high altitude)
            if (ty > 6.0f) continue;
            Mat4 tm = mat4_translate(tx, ty, tz);
            // Slight random rotation per tree
            float rot = hash2(tx * 0.13f, tz * 0.19f) * 6.28f;
            tm = mat4_mul(tm, mat4_rotY(rot));
            setModel(tm);
            drawVAO(g_vaoTree, N_TREE);
        }
    }

    // 3. Player character
    float bobY   = (moving ? sinf(g_walkT * 2.0f) * 0.03f : 0.0f);
    float jumpArc = g_jumpY - terrainH(g_px, g_pz);   // height above ground
    Mat4 playerBase = mat4_translate(g_px, g_py + 1.0f + jumpArc + bobY, g_pz);
    playerBase = mat4_mul(playerBase, mat4_rotY(g_facing));
    drawCharacter(playerBase);
}

JNIEXPORT void JNICALL
Java_com_game_procedural_MainActivity_triggerAction(JNIEnv*, jobject, jint id) {
    switch (id) {
        case 1: g_slashT = 1.0f; break;                           // Attack
        case 2: g_block  = true; break;                           // Block start
        case 3: g_block  = false; break;                          // Block end
        case 4:                                                    // Jump
            if (g_jumpY <= terrainH(g_px, g_pz) + 0.05f)
                g_jumpVY = 0.38f;
            break;
        case 6: g_bashT = 1.0f; g_block = false; break;          // Shield bash
    }
}

JNIEXPORT jfloat JNICALL
Java_com_game_procedural_MainActivity_getCameraYaw(JNIEnv*, jobject) {
    return g_camYaw;
}

} // extern "C"
EOF

echo "[generate_engine.sh] native-lib.cpp written."
