#!/bin/bash
# File: runtime/generate_models.sh
# EndlessRPG v6 — Pure shell model generator, no Blender.
# Produces AllModels.h: pos(x,y,z)+color(r,g,b) per vertex, 6 floats/vert.
# Symbol names match native-lib.cpp exactly:
#   M_TORSO N_TORSO  M_NECK N_NECK  M_HEAD N_HEAD
#   M_UP_LIMB N_UP_LIMB  M_LOW_LIMB N_LOW_LIMB
#   M_HAND N_HAND  M_FOOT N_FOOT
#   M_SWORD N_SWORD  M_SHIELD N_SHIELD
#   M_TREE N_TREE  M_ROCK N_ROCK

set -e
mkdir -p app/src/main/cpp/models

cat << 'HEOF' > app/src/main/cpp/models/AllModels.h
// Auto-generated by runtime/generate_models.sh — DO NOT EDIT
// Vertex layout: x,y,z,r,g,b  (6 floats/vertex, 36 verts per box face-set)
#pragma once

// BOX6(hw,hh,hd, cr,cg,cb)
// Emits 36 verts (6 faces x 2 tris x 3 verts) with face-baked shading.
// shade: top=1.0, front=0.85, sides=0.70, back=0.60, bottom=0.50
#define BOX6(hw,hh,hd,cr,cg,cb) \
    -(hw), (hh), (hd),  (cr)*0.85f,(cg)*0.85f,(cb)*0.85f, \
     (hw), (hh), (hd),  (cr)*0.85f,(cg)*0.85f,(cb)*0.85f, \
    -(hw),-(hh), (hd),  (cr)*0.85f,(cg)*0.85f,(cb)*0.85f, \
     (hw), (hh), (hd),  (cr)*0.85f,(cg)*0.85f,(cb)*0.85f, \
     (hw),-(hh), (hd),  (cr)*0.85f,(cg)*0.85f,(cb)*0.85f, \
    -(hw),-(hh), (hd),  (cr)*0.85f,(cg)*0.85f,(cb)*0.85f, \
     (hw), (hh),-(hd),  (cr)*0.60f,(cg)*0.60f,(cb)*0.60f, \
    -(hw), (hh),-(hd),  (cr)*0.60f,(cg)*0.60f,(cb)*0.60f, \
     (hw),-(hh),-(hd),  (cr)*0.60f,(cg)*0.60f,(cb)*0.60f, \
    -(hw), (hh),-(hd),  (cr)*0.60f,(cg)*0.60f,(cb)*0.60f, \
    -(hw),-(hh),-(hd),  (cr)*0.60f,(cg)*0.60f,(cb)*0.60f, \
     (hw),-(hh),-(hd),  (cr)*0.60f,(cg)*0.60f,(cb)*0.60f, \
    -(hw), (hh),-(hd),  (cr)*0.70f,(cg)*0.70f,(cb)*0.70f, \
    -(hw), (hh), (hd),  (cr)*0.70f,(cg)*0.70f,(cb)*0.70f, \
    -(hw),-(hh),-(hd),  (cr)*0.70f,(cg)*0.70f,(cb)*0.70f, \
    -(hw), (hh), (hd),  (cr)*0.70f,(cg)*0.70f,(cb)*0.70f, \
    -(hw),-(hh), (hd),  (cr)*0.70f,(cg)*0.70f,(cb)*0.70f, \
    -(hw),-(hh),-(hd),  (cr)*0.70f,(cg)*0.70f,(cb)*0.70f, \
     (hw), (hh), (hd),  (cr)*0.70f,(cg)*0.70f,(cb)*0.70f, \
     (hw), (hh),-(hd),  (cr)*0.70f,(cg)*0.70f,(cb)*0.70f, \
     (hw),-(hh), (hd),  (cr)*0.70f,(cg)*0.70f,(cb)*0.70f, \
     (hw), (hh),-(hd),  (cr)*0.70f,(cg)*0.70f,(cb)*0.70f, \
     (hw),-(hh),-(hd),  (cr)*0.70f,(cg)*0.70f,(cb)*0.70f, \
     (hw),-(hh), (hd),  (cr)*0.70f,(cg)*0.70f,(cb)*0.70f, \
    -(hw), (hh),-(hd),  (cr)*1.00f,(cg)*1.00f,(cb)*1.00f, \
     (hw), (hh),-(hd),  (cr)*1.00f,(cg)*1.00f,(cb)*1.00f, \
    -(hw), (hh), (hd),  (cr)*1.00f,(cg)*1.00f,(cb)*1.00f, \
     (hw), (hh),-(hd),  (cr)*1.00f,(cg)*1.00f,(cb)*1.00f, \
     (hw), (hh), (hd),  (cr)*1.00f,(cg)*1.00f,(cb)*1.00f, \
    -(hw), (hh), (hd),  (cr)*1.00f,(cg)*1.00f,(cb)*1.00f, \
    -(hw),-(hh), (hd),  (cr)*0.50f,(cg)*0.50f,(cb)*0.50f, \
     (hw),-(hh), (hd),  (cr)*0.50f,(cg)*0.50f,(cb)*0.50f, \
    -(hw),-(hh),-(hd),  (cr)*0.50f,(cg)*0.50f,(cb)*0.50f, \
     (hw),-(hh), (hd),  (cr)*0.50f,(cg)*0.50f,(cb)*0.50f, \
     (hw),-(hh),-(hd),  (cr)*0.50f,(cg)*0.50f,(cb)*0.50f, \
    -(hw),-(hh),-(hd),  (cr)*0.50f,(cg)*0.50f,(cb)*0.50f

// ── Character ────────────────────────────────────────────────────────────────
static const float M_TORSO[]    = { BOX6(0.20f,0.30f,0.12f, 0.28f,0.31f,0.38f) };
static const int   N_TORSO      = 36;

static const float M_NECK[]     = { BOX6(0.07f,0.08f,0.07f, 0.62f,0.52f,0.44f) };
static const int   N_NECK       = 36;

static const float M_HEAD[]     = { BOX6(0.14f,0.14f,0.14f, 0.30f,0.32f,0.36f) };
static const int   N_HEAD       = 36;

static const float M_UP_LIMB[]  = { BOX6(0.07f,0.20f,0.07f, 0.26f,0.28f,0.34f) };
static const int   N_UP_LIMB    = 36;

static const float M_LOW_LIMB[] = { BOX6(0.06f,0.19f,0.06f, 0.24f,0.26f,0.32f) };
static const int   N_LOW_LIMB   = 36;

static const float M_HAND[]     = { BOX6(0.06f,0.06f,0.05f, 0.20f,0.18f,0.16f) };
static const int   N_HAND       = 36;

static const float M_FOOT[]     = { BOX6(0.07f,0.05f,0.10f, 0.18f,0.16f,0.14f) };
static const int   N_FOOT       = 36;

// ── Equipment ────────────────────────────────────────────────────────────────
// Sword = blade box + crossguard box (72 verts)
static const float M_SWORD[] = {
    BOX6(0.020f,0.55f,0.005f, 0.58f,0.60f,0.65f),
    BOX6(0.180f,0.025f,0.018f, 0.48f,0.50f,0.55f)
};
static const int   N_SWORD = 72;

// Shield = main plate + boss (72 verts)
static const float M_SHIELD[] = {
    BOX6(0.22f,0.30f,0.025f, 0.30f,0.22f,0.14f),
    BOX6(0.06f,0.06f,0.045f, 0.40f,0.40f,0.42f)
};
static const int   N_SHIELD = 72;

// ── Environment ──────────────────────────────────────────────────────────────
// Tree = trunk box + canopy box offset upward (72 verts)
// Canopy is hand-listed with Y offset +1.0 (centre at trunk top)
static const float M_TREE[] = {
    // Trunk — dark bark
    BOX6(0.14f,1.00f,0.14f, 0.22f,0.16f,0.10f),
    // Canopy — front face (y range 0.60..1.60)
    -0.55f, 1.60f,  0.55f,  0.12f,0.22f,0.09f,
     0.55f, 1.60f,  0.55f,  0.12f,0.22f,0.09f,
    -0.55f, 0.60f,  0.55f,  0.12f,0.22f,0.09f,
     0.55f, 1.60f,  0.55f,  0.12f,0.22f,0.09f,
     0.55f, 0.60f,  0.55f,  0.12f,0.22f,0.09f,
    -0.55f, 0.60f,  0.55f,  0.12f,0.22f,0.09f,
    // back
     0.55f, 1.60f, -0.55f,  0.10f,0.19f,0.08f,
    -0.55f, 1.60f, -0.55f,  0.10f,0.19f,0.08f,
     0.55f, 0.60f, -0.55f,  0.10f,0.19f,0.08f,
    -0.55f, 1.60f, -0.55f,  0.10f,0.19f,0.08f,
    -0.55f, 0.60f, -0.55f,  0.10f,0.19f,0.08f,
     0.55f, 0.60f, -0.55f,  0.10f,0.19f,0.08f,
    // left
    -0.55f, 1.60f, -0.55f,  0.11f,0.20f,0.08f,
    -0.55f, 1.60f,  0.55f,  0.11f,0.20f,0.08f,
    -0.55f, 0.60f, -0.55f,  0.11f,0.20f,0.08f,
    -0.55f, 1.60f,  0.55f,  0.11f,0.20f,0.08f,
    -0.55f, 0.60f,  0.55f,  0.11f,0.20f,0.08f,
    -0.55f, 0.60f, -0.55f,  0.11f,0.20f,0.08f,
    // right
     0.55f, 1.60f,  0.55f,  0.11f,0.20f,0.08f,
     0.55f, 1.60f, -0.55f,  0.11f,0.20f,0.08f,
     0.55f, 0.60f,  0.55f,  0.11f,0.20f,0.08f,
     0.55f, 1.60f, -0.55f,  0.11f,0.20f,0.08f,
     0.55f, 0.60f, -0.55f,  0.11f,0.20f,0.08f,
     0.55f, 0.60f,  0.55f,  0.11f,0.20f,0.08f,
    // top
    -0.55f, 1.60f, -0.55f,  0.14f,0.26f,0.10f,
     0.55f, 1.60f, -0.55f,  0.14f,0.26f,0.10f,
    -0.55f, 1.60f,  0.55f,  0.14f,0.26f,0.10f,
     0.55f, 1.60f, -0.55f,  0.14f,0.26f,0.10f,
     0.55f, 1.60f,  0.55f,  0.14f,0.26f,0.10f,
    -0.55f, 1.60f,  0.55f,  0.14f,0.26f,0.10f,
    // bottom
    -0.55f, 0.60f,  0.55f,  0.08f,0.14f,0.06f,
     0.55f, 0.60f,  0.55f,  0.08f,0.14f,0.06f,
    -0.55f, 0.60f, -0.55f,  0.08f,0.14f,0.06f,
     0.55f, 0.60f,  0.55f,  0.08f,0.14f,0.06f,
     0.55f, 0.60f, -0.55f,  0.08f,0.14f,0.06f,
    -0.55f, 0.60f, -0.55f,  0.08f,0.14f,0.06f
};
static const int N_TREE = 72;

// Rock — warm grey-brown flattened box
static const float M_ROCK[] = { BOX6(0.38f,0.22f,0.34f, 0.42f,0.38f,0.32f) };
static const int   N_ROCK   = 36;

HEOF

echo "[generate_models.sh] AllModels.h written — symbols match native-lib.cpp."
