# File: runtime/python/generate_realistic_assets.py
# Blender Python script.
# Generates supplementary environmental assets (tree, rock variants)
# that are SEPARATE from the main AllModels.h bake.
# Exports to tree_model.h for direct inclusion in engine.cpp.

import bpy
import bmesh
import random


def export_to_cpp_header(obj, filepath: str, array_name: str):
    """Triangulate and export a single mesh as a C pos+normal header."""
    dg = bpy.context.evaluated_depsgraph_get()
    eval_obj = obj.evaluated_get(dg)
    mesh = eval_obj.to_mesh()

    bm = bmesh.new()
    bm.from_mesh(mesh)
    bmesh.ops.triangulate(bm, faces=bm.faces)
    bm.to_mesh(mesh)
    bm.free()
    mesh.calc_normals_split()

    verts = []
    for tri in mesh.loop_triangles:
        for li in tri.loops:
            v = mesh.vertices[mesh.loops[li].vertex_index]
            n = mesh.loops[li].normal
            # Blender Z-up → OpenGL Y-up
            verts += [v.co.x * 0.5, v.co.z * 0.5, -v.co.y * 0.5,
                      n.x, n.z, -n.y]

    eval_obj.to_mesh_clear()

    with open(filepath, 'w') as f:
        f.write(f"// Auto-generated by generate_realistic_assets.py\n")
        f.write(f"#pragma once\n")
        f.write(f"const float {array_name}_verts[] = {{\n")
        for i in range(0, len(verts), 6):
            f.write(f"    {verts[i]:.5f}f,{verts[i+1]:.5f}f,{verts[i+2]:.5f}f, "
                    f"{verts[i+3]:.5f}f,{verts[i+4]:.5f}f,{verts[i+5]:.5f}f,\n")
        f.write("};\n")
        f.write(f"const int {array_name}_count = {len(verts) // 6};\n")
    print(f"Exported {array_name}: {len(verts)//6} verts → {filepath}")


def build_realistic_tree():
    """
    Realistic deciduous tree with:
    - Tapered trunk widening at the base (two cylinders)
    - Natural multi-lobe canopy (no floating balls, tightly grouped)
    """
    random.seed(123)

    bpy.ops.object.select_all(action='SELECT')
    bpy.ops.object.delete()

    # Base of trunk (wider)
    bpy.ops.mesh.primitive_cylinder_add(vertices=12, radius=0.22, depth=0.6,
                                        location=(0, 0, 0.3))
    bpy.ops.object.modifier_add(type='SUBSURF')
    bpy.context.object.modifiers[-1].levels = 1

    # Main trunk (narrower, taller)
    bpy.ops.mesh.primitive_cylinder_add(vertices=10, radius=0.15, depth=2.0,
                                        location=(0, 0, 1.6))
    bpy.ops.object.modifier_add(type='SUBSURF')
    bpy.context.object.modifiers[-1].levels = 1

    # Canopy — tightly clustered spheres, no random outliers
    canopy = [
        (0.00,  0.00, 3.20, 1.05),
        ( 0.55,  0.30, 2.95, 0.75),
        (-0.50,  0.40, 3.05, 0.70),
        ( 0.25, -0.55, 2.90, 0.68),
        (-0.35, -0.30, 3.30, 0.62),
        ( 0.60, -0.10, 3.45, 0.52),
        (-0.50,  0.05, 3.50, 0.50),
        ( 0.00,  0.60, 3.60, 0.47),
        ( 0.00,  0.00, 3.85, 0.55),
    ]
    for cx, cy, cz, cr in canopy:
        bpy.ops.mesh.primitive_uv_sphere_add(segments=10, ring_count=8,
                                             radius=cr, location=(cx, cy, cz))
        bpy.ops.object.modifier_add(type='SUBSURF')
        bpy.context.object.modifiers[-1].levels = 1

    # Join all parts
    bpy.ops.object.select_all(action='SELECT')
    bpy.context.view_layer.objects.active = bpy.context.selected_objects[0]
    bpy.ops.object.join()
    bpy.ops.object.transform_apply(location=True, rotation=True, scale=True)

    return bpy.context.active_object


if __name__ == "__main__":
    tree = build_realistic_tree()
    export_to_cpp_header(tree, "app/src/main/cpp/tree_model.h", "tree")
    print("generate_realistic_assets.py complete.")
