#version 310 es

layout(location = 0) in vec3 aPos;

// Access the 1D SSBO generated by grass.comp
struct Blade { vec4 pos; vec4 dir; };
layout(std430, binding = 0) buffer GrassBuffer { Blade blades[]; };

uniform mat4 u_MVP;

out vec3 vWorldPos;
out vec3 vNormal;
out float vHeightTaper;

void main() {
    Blade b = blades[gl_InstanceID];
    vec3 basePos = b.pos.xyz;
    vec3 windDir = b.dir.xyz;

    // We assume the top of the grass geometry is around Y = 1.0 in local space
    float normalizedHeight = clamp(aPos.y, 0.0, 1.0);
    vHeightTaper = normalizedHeight;

    // Apply wind displacement primarily to the top of the blade (exponential bend)
    vec3 animatedPos = aPos;
    animatedPos += windDir * (normalizedHeight * normalizedHeight);

    // Give each blade a random rotation around the Y-axis so they look organic
    float rotHash = fract(sin(dot(basePos.xz, vec2(12.9898, 78.233))) * 43758.5453) * 6.28318;
    float s = sin(rotHash);
    float c = cos(rotHash);
    mat3 rotY = mat3(
        c, 0, s,
        0, 1, 0,
       -s, 0, c
    );

    // Generate a basic normal pointing outward from the flat blade face
    vNormal = normalize(rotY * vec3(0.0, 0.0, 1.0));

    // Rotate the local blade and move it to its world position
    vec3 worldPos = basePos + (rotY * animatedPos);
    
    vWorldPos = worldPos;
    gl_Position = u_MVP * vec4(worldPos, 1.0);
}
